# Generated by Django 4.0.4 on 2023-12-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='limit',
            new_name='cost',
        ),
    ]
